//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspFinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class St_Taken_Course
    {
        public int id { get; set; }
        public Nullable<int> st_id { get; set; }
        public string cs_id { get; set; }
    }
}
