//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace AspFinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [Key]
        public string id { get; set; }

        public string name { get; set; }
        public string department { get; set; }
        public string semester { get; set; }
        public Nullable<int> batch { get; set; }
        public string section { get; set; }
        public string gender { get; set; }
        public string phone { get; set; }
    }
}
