//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspFinalProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AspProjectDBEntitiestakenCourse : DbContext
    {
        public AspProjectDBEntitiestakenCourse()
            : base("name=AspProjectDBEntitiestakenCourse")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<St_Taken_Course> St_Taken_Course { get; set; }
        public virtual DbSet<Tc_Taken_Course> Tc_Taken_Course { get; set; }
    }
}
